//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	store "github.com/setcreed/store-apiserver/pkg/apis/store"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DBConfig)(nil), (*store.DBConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DBConfig_To_store_DBConfig(a.(*DBConfig), b.(*store.DBConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.DBConfig)(nil), (*DBConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_DBConfig_To_v1alpha1_DBConfig(a.(*store.DBConfig), b.(*DBConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SQLConfig)(nil), (*store.SQLConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SQLConfig_To_store_SQLConfig(a.(*SQLConfig), b.(*store.SQLConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.SQLConfig)(nil), (*SQLConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_SQLConfig_To_v1alpha1_SQLConfig(a.(*store.SQLConfig), b.(*SQLConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Select)(nil), (*store.Select)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Select_To_store_Select(a.(*Select), b.(*store.Select), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.Select)(nil), (*Select)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_Select_To_v1alpha1_Select(a.(*store.Select), b.(*Select), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreService)(nil), (*store.StoreService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreService_To_store_StoreService(a.(*StoreService), b.(*store.StoreService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.StoreService)(nil), (*StoreService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_StoreService_To_v1alpha1_StoreService(a.(*store.StoreService), b.(*StoreService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreServiceList)(nil), (*store.StoreServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreServiceList_To_store_StoreServiceList(a.(*StoreServiceList), b.(*store.StoreServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.StoreServiceList)(nil), (*StoreServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_StoreServiceList_To_v1alpha1_StoreServiceList(a.(*store.StoreServiceList), b.(*StoreServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreServiceSpec)(nil), (*store.StoreServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreServiceSpec_To_store_StoreServiceSpec(a.(*StoreServiceSpec), b.(*store.StoreServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.StoreServiceSpec)(nil), (*StoreServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_StoreServiceSpec_To_v1alpha1_StoreServiceSpec(a.(*store.StoreServiceSpec), b.(*StoreServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StoreServiceStatus)(nil), (*store.StoreServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StoreServiceStatus_To_store_StoreServiceStatus(a.(*StoreServiceStatus), b.(*store.StoreServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*store.StoreServiceStatus)(nil), (*StoreServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_store_StoreServiceStatus_To_v1alpha1_StoreServiceStatus(a.(*store.StoreServiceStatus), b.(*StoreServiceStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DBConfig_To_store_DBConfig(in *DBConfig, out *store.DBConfig, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Dsn = in.Dsn
	out.MaxOpenConn = in.MaxOpenConn
	out.MaxLifeTime = in.MaxLifeTime
	out.MaxIdleConn = in.MaxIdleConn
	return nil
}

// Convert_v1alpha1_DBConfig_To_store_DBConfig is an autogenerated conversion function.
func Convert_v1alpha1_DBConfig_To_store_DBConfig(in *DBConfig, out *store.DBConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DBConfig_To_store_DBConfig(in, out, s)
}

func autoConvert_store_DBConfig_To_v1alpha1_DBConfig(in *store.DBConfig, out *DBConfig, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Dsn = in.Dsn
	out.MaxOpenConn = in.MaxOpenConn
	out.MaxLifeTime = in.MaxLifeTime
	out.MaxIdleConn = in.MaxIdleConn
	return nil
}

// Convert_store_DBConfig_To_v1alpha1_DBConfig is an autogenerated conversion function.
func Convert_store_DBConfig_To_v1alpha1_DBConfig(in *store.DBConfig, out *DBConfig, s conversion.Scope) error {
	return autoConvert_store_DBConfig_To_v1alpha1_DBConfig(in, out, s)
}

func autoConvert_v1alpha1_SQLConfig_To_store_SQLConfig(in *SQLConfig, out *store.SQLConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Sql = in.Sql
	out.Select = (*store.Select)(unsafe.Pointer(in.Select))
	return nil
}

// Convert_v1alpha1_SQLConfig_To_store_SQLConfig is an autogenerated conversion function.
func Convert_v1alpha1_SQLConfig_To_store_SQLConfig(in *SQLConfig, out *store.SQLConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_SQLConfig_To_store_SQLConfig(in, out, s)
}

func autoConvert_store_SQLConfig_To_v1alpha1_SQLConfig(in *store.SQLConfig, out *SQLConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.Sql = in.Sql
	out.Select = (*Select)(unsafe.Pointer(in.Select))
	return nil
}

// Convert_store_SQLConfig_To_v1alpha1_SQLConfig is an autogenerated conversion function.
func Convert_store_SQLConfig_To_v1alpha1_SQLConfig(in *store.SQLConfig, out *SQLConfig, s conversion.Scope) error {
	return autoConvert_store_SQLConfig_To_v1alpha1_SQLConfig(in, out, s)
}

func autoConvert_v1alpha1_Select_To_store_Select(in *Select, out *store.Select, s conversion.Scope) error {
	out.Sql = in.Sql
	return nil
}

// Convert_v1alpha1_Select_To_store_Select is an autogenerated conversion function.
func Convert_v1alpha1_Select_To_store_Select(in *Select, out *store.Select, s conversion.Scope) error {
	return autoConvert_v1alpha1_Select_To_store_Select(in, out, s)
}

func autoConvert_store_Select_To_v1alpha1_Select(in *store.Select, out *Select, s conversion.Scope) error {
	out.Sql = in.Sql
	return nil
}

// Convert_store_Select_To_v1alpha1_Select is an autogenerated conversion function.
func Convert_store_Select_To_v1alpha1_Select(in *store.Select, out *Select, s conversion.Scope) error {
	return autoConvert_store_Select_To_v1alpha1_Select(in, out, s)
}

func autoConvert_v1alpha1_StoreService_To_store_StoreService(in *StoreService, out *store.StoreService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_StoreServiceSpec_To_store_StoreServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_StoreServiceStatus_To_store_StoreServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_StoreService_To_store_StoreService is an autogenerated conversion function.
func Convert_v1alpha1_StoreService_To_store_StoreService(in *StoreService, out *store.StoreService, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreService_To_store_StoreService(in, out, s)
}

func autoConvert_store_StoreService_To_v1alpha1_StoreService(in *store.StoreService, out *StoreService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_store_StoreServiceSpec_To_v1alpha1_StoreServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_store_StoreServiceStatus_To_v1alpha1_StoreServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_store_StoreService_To_v1alpha1_StoreService is an autogenerated conversion function.
func Convert_store_StoreService_To_v1alpha1_StoreService(in *store.StoreService, out *StoreService, s conversion.Scope) error {
	return autoConvert_store_StoreService_To_v1alpha1_StoreService(in, out, s)
}

func autoConvert_v1alpha1_StoreServiceList_To_store_StoreServiceList(in *StoreServiceList, out *store.StoreServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]store.StoreService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_StoreServiceList_To_store_StoreServiceList is an autogenerated conversion function.
func Convert_v1alpha1_StoreServiceList_To_store_StoreServiceList(in *StoreServiceList, out *store.StoreServiceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreServiceList_To_store_StoreServiceList(in, out, s)
}

func autoConvert_store_StoreServiceList_To_v1alpha1_StoreServiceList(in *store.StoreServiceList, out *StoreServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]StoreService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_store_StoreServiceList_To_v1alpha1_StoreServiceList is an autogenerated conversion function.
func Convert_store_StoreServiceList_To_v1alpha1_StoreServiceList(in *store.StoreServiceList, out *StoreServiceList, s conversion.Scope) error {
	return autoConvert_store_StoreServiceList_To_v1alpha1_StoreServiceList(in, out, s)
}

func autoConvert_v1alpha1_StoreServiceSpec_To_store_StoreServiceSpec(in *StoreServiceSpec, out *store.StoreServiceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_DBConfig_To_store_DBConfig(&in.DbConfig, &out.DbConfig, s); err != nil {
		return err
	}
	out.SqlConfig = *(*[]*store.SQLConfig)(unsafe.Pointer(&in.SqlConfig))
	return nil
}

// Convert_v1alpha1_StoreServiceSpec_To_store_StoreServiceSpec is an autogenerated conversion function.
func Convert_v1alpha1_StoreServiceSpec_To_store_StoreServiceSpec(in *StoreServiceSpec, out *store.StoreServiceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreServiceSpec_To_store_StoreServiceSpec(in, out, s)
}

func autoConvert_store_StoreServiceSpec_To_v1alpha1_StoreServiceSpec(in *store.StoreServiceSpec, out *StoreServiceSpec, s conversion.Scope) error {
	if err := Convert_store_DBConfig_To_v1alpha1_DBConfig(&in.DbConfig, &out.DbConfig, s); err != nil {
		return err
	}
	out.SqlConfig = *(*[]*SQLConfig)(unsafe.Pointer(&in.SqlConfig))
	return nil
}

// Convert_store_StoreServiceSpec_To_v1alpha1_StoreServiceSpec is an autogenerated conversion function.
func Convert_store_StoreServiceSpec_To_v1alpha1_StoreServiceSpec(in *store.StoreServiceSpec, out *StoreServiceSpec, s conversion.Scope) error {
	return autoConvert_store_StoreServiceSpec_To_v1alpha1_StoreServiceSpec(in, out, s)
}

func autoConvert_v1alpha1_StoreServiceStatus_To_store_StoreServiceStatus(in *StoreServiceStatus, out *store.StoreServiceStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Ready = in.Ready
	return nil
}

// Convert_v1alpha1_StoreServiceStatus_To_store_StoreServiceStatus is an autogenerated conversion function.
func Convert_v1alpha1_StoreServiceStatus_To_store_StoreServiceStatus(in *StoreServiceStatus, out *store.StoreServiceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_StoreServiceStatus_To_store_StoreServiceStatus(in, out, s)
}

func autoConvert_store_StoreServiceStatus_To_v1alpha1_StoreServiceStatus(in *store.StoreServiceStatus, out *StoreServiceStatus, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Ready = in.Ready
	return nil
}

// Convert_store_StoreServiceStatus_To_v1alpha1_StoreServiceStatus is an autogenerated conversion function.
func Convert_store_StoreServiceStatus_To_v1alpha1_StoreServiceStatus(in *store.StoreServiceStatus, out *StoreServiceStatus, s conversion.Scope) error {
	return autoConvert_store_StoreServiceStatus_To_v1alpha1_StoreServiceStatus(in, out, s)
}
